### ISSUE TITLE
Deleted Files Still Appear in Tree in Learn IDE

### ISSUE THREAD

**Issue by RoyEriksen** [learn-co-curriculum/setting-up-a-new-site#11]
Have successfully deleted files, i.e. they don't appear with command ls. However, folders still appear on the left in the tree view. I've tried right clicking and selecting delete on these files but it doesn't work (I get a prompt asking if I'm sure I want to delete the file, but after clicking move to trash nothing happens.)

**Comment by aturkewi** [comment]
Hey @RoyEriksen We've updated the Learn IDE so that if you just type in `exit` or if you restart the IDE, it will sync all your local files to match what's on the server :)

Please let us know if you're still running into any issues with this!
