### ISSUE TITLE
Link Error

### ISSUE THREAD

**Issue by Argonity** [learn-co-curriculum/setting-up-a-new-site#12]
**This link:** "Click here to save the intro pic used in this code along." does not work. 

**Error when clicked:** 

This site can’t be reached

ironboard-curriculum-content.s3.amazonaws.com’s server DNS address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
