### ISSUE TITLE
Confusing for Nitrous users

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/setting-up-a-new-site#4]
Students have a hard time following along given there is no downloads folder there, and they are unsure how to get their images into Nitrous, etc.

**Comment by jongrover** [comment]
@joe @AnnJohn We will need to create new content that takes into account both nitrous users as well as OsX users.

**Comment by AnnJohn** [comment]
going to close this issue since we're moving off of Nitrous.

**Comment by matbalez-test33** [comment]
@AnnJohn are you confident that the instructions are clear/work in the Learn IDE?
