### ISSUE TITLE
.gitignore files

### ISSUE THREAD

**Issue by hebersandoval** [learn-co-curriculum/setting-up-a-new-site#5]
when accessing this files to copy and paste, as directed by the video (3:30 mark), i was not able to find them. it seems that they were moved elsewhere or no longer available. please provide no path, if available. thank you. heber.

**Comment by jongrover** [comment]
@hscoder I added a direct link in the README.md file thanks for your suggestion. Here is the link as well: https://gist.githubusercontent.com/octocat/9257657/raw/3f9569e65df83a7b328b39a091f0ce9c6efc6429/.gitignore

**Comment by hebersandoval** [comment]
Jonathan,

This is great! 

Thank you so much.

Héber Sandoval 

-----Original Message-----
