### ISSUE TITLE
error--->git: 'co' is not a git command

### ISSUE THREAD

**Issue by hebersandoval** [learn-co-curriculum/setting-up-a-new-site#6]
when trying to make a branch using the following command: "git co -b main-pages I get this error:

error--->git: 'co' is not a git command

This code below seems to fix the problem:

git checkout -b main-pages

**Comment by AnnJohn** [comment]
Hi @hscoder the issue is probably due to the fact that your bash profile isn't set up correctly and you may need to re-run the setup. But please use the Ask a Question tool and someone will get back to you right away and help you out.

**Comment by hebersandoval** [comment]
Ann,

I'll ask for help in the "ask a question" section. 

Thank you for your help.

Héber Sandoval 

-----Original Message-----
