### ISSUE TITLE
'git co -b main-pages' commands doesn't work on git version 2.7.4 (Apple Git-66)

### ISSUE THREAD

**Issue by eskayio** [learn-co-curriculum/setting-up-a-new-site#8]
I'm using git version 2.7.4 (Apple Git-66) and at around minute 7:55 in the video a command is used to create a new branch called 'main-pages' and switch to that branch.

I receive the following error when I use that command:

git: 'co' is not a git command. See 'git --help'.

Did you mean one of these?
    commit
    clone
    log

The following command does work:

'git branch main-pages'

then...

'git checkout main-pages'

**Comment by gj** [comment]
Hi @eskayio,

You've probably already figured this out, but on the off-chance that someone else has the same problem:

`git co -b <branch-name>` is an alias for `git checkout -b <branch-name>`. The `-b` flag creates a new branch that is then checked out.

Git aliases are defined in the `.gitconfig` file in your home directory. Learn's manual setup instructions for local development contain a suggested `.gitconfig` that includes the `co` alias, among many others. Here are the relevant instructions:

> 1. Backup your .bash_profile with `mv ~/.bash_profile{,.bak}`
> 2. `curl "https://raw.githubusercontent.com/flatiron-school/dotfiles/master/linux_bash_profile" -o "$HOME/.bash_profile"` -- Your bash profile loads up every time you open a terminal window. The Learn bash_profile is designed to load up a bunch of shortcuts for you as well as make sure that RVM loads up every time you open the terminal. I recommend you take a look at this file and even see if there are any shortcuts of your own that you'd like to add! Note: this will overwrite your existing bash profile, so back up first if you want to.
